apiVersion: v1
kind: Secret
metadata:
  name: scg-overlay
type: Opaque
stringData:
  overlay.yaml: |
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      namespace: spring-cloud-gateway
      name: system:openshift:scc:privileged
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:openshift:scc:privileged
    subjects:
    - kind: ServiceAccount
      name: spring-cloud-gateway
      namespace: spring-cloud-gateway