apiVersion: v1
kind: Secret
metadata:
  name: tcs-overlay
type: Opaque
stringData:
  overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind":"DaemonSet", "metadata": {"name":"istio-cni-node"}}), expects=1
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by="name"
          - name: install-cni
            env:
            #@overlay/match by=overlay.index(0)
            #@overlay/insert before=True
            - name: CNI_CONF_NAME
              value: "istio-cni.conf"
            #@overlay/match by="name"
            - name: CNI_NET_DIR
              value: /etc/cni/multus/net.d
            #@overlay/match by="name"
            - name: CHAINED_CNI_PLUGIN
              value: "false"
          volumes:
          #@overlay/match by="name"
          - name: cni-bin-dir
            hostPath:
              path: /var/lib/cni/bin
          #@overlay/match by="name"
          - name: cni-net-dir
            hostPath:
              path: /etc/cni/multus/net.d
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      namespace: istio-system
      name: system:openshift:scc:privileged
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:openshift:scc:privileged
    subjects:
    - kind: ServiceAccount
      name: istiod
      namespace: istio-system
    - kind: ServiceAccount
      name: istio-egressgateway
      namespace: istio-system
    - kind: ServiceAccount
      name: istio-ingressgateway
      namespace: istio-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      namespace: istio-cni-system
      name: system:openshift:scc:privileged
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:openshift:scc:privileged
    subjects:
    - kind: ServiceAccount
      name: istio-cni
      namespace: istio-cni-system
